### ISSUE TITLE
Support for different devices

### ISSUE THREAD

**Issue by jonasmalacofilho** [Frick-David/liquidctlgui#1]
Hi David,

Are you planning to build a general solution for all devices supported by liquidctl or something than can only handle the HUE 2 and Smart Device (V2)?

**Comment by David-Frick** [comment]
I am going to start with just the HUE 2 and Smart Device then go from there.

**Comment by jonasmalacofilho** [comment]
You already clarified this to me.  Quote from #2:

> Control all RGB devices that liquidctl can

Feel free to close this issue then.

**Comment by Frick-David** [comment]
@jonasmalacofilho will do!
